# Generated by Django 6.0.6 on 2026-06-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'place',
                    models.CharField(
                        help_text='Где вы хотите развить привычку?', max_length=100, verbose_name='Место'
                    ),
                ),
                ('time', models.TimeField(help_text='Когда вы хотите развить привычку?', verbose_name='Время')),
                (
                    'action',
                    models.CharField(
                        help_text='Какое действие вы хотите развить в привычку?',
                        max_length=100,
                        verbose_name='Действие',
                    ),
                ),
                (
                    'is_pleasant',
                    models.BooleanField(
                        default=False,
                        help_text='Отметьте, если эта привычка приятная для вас',
                        verbose_name='Признак приятной привычки',
                    ),
                ),
                (
                    'periodicity',
                    models.IntegerField(
                        help_text='Сколько раз в неделю вы хотите развивать эту привычку?',
                        verbose_name='Периодичность',
                    ),
                ),
                (
                    'reward',
                    models.CharField(
                        blank=True,
                        help_text='Какую награду вы хотите получить за развитие этой привычки?',
                        max_length=100,
                        null=True,
                        verbose_name='Награда',
                    ),
                ),
                (
                    'time_to_complete',
                    models.IntegerField(
                        help_text='Сколько секунд Вам требуется на выполнение привычки? (от 1 до 120)',
                        verbose_name='Время на выполнение',
                    ),
                ),
                (
                    'is_public',
                    models.BooleanField(
                        default=False,
                        help_text='Отметьте, если вы хотите, чтобы эта привычка была видна другим пользователям',
                        verbose_name='Публичная привычка',
                    ),
                ),
                (
                    'connected_habit',
                    models.ForeignKey(
                        blank=True,
                        help_text='Выберите привычку, с которой связана эта привычка',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='habit_tracker.habit',
                        verbose_name='Связанная привычка',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
